---
- name: Demo
  hosts: east
  tasks:
   - name: Task1
     ansible.builtin.command: id
   - name: Task2
     ansible.builtin.shell: uptime
   - name: Task3
     ansible.builtin.yum: 
       name: dialog
       state: absent
      
...
