---
- name: DEmo of webserver configuration
  hosts: servera
  tasks:
   - name: SELinux type is set to samba_share_t
     ansible.builtin.file:
      path: /tmp/test
      setype: samba_share_t
      state: touch 
...
