---
- name: DEmo of webserver configuration
  hosts: servera
  tasks:
      - name: Install package
        ansible.builtin.yum:
         name: httpd
         state: present
      - name: STart and enable service
        ansible.builtin.service:
         name: httpd
         state: started
         enabled: yes
      - name: Deliver the content
        ansible.builtin.copy: 
         content: |
           <html>
           <head>
           <title> Chapter 05 </title>
           </head>
           <body>
           <h1>Demo of blockinfile module</h1>
           </body>
           </html>
         dest: /var/www/html/index.html
      - name: OPen firewall port   
        ansible.posix.firewalld:
         service: http
         immediate: yes
         permanent: yes
         state: enabled



           
...
