---
- name: demo of ignore errors
  hosts: 'all:!east'
  ignore_errors: yes
  tasks:
   - name: task1
     command: ls
   - name: task2
     command: notacommand
   - name: task3
     command: uptime
...
