---
- name: demo of ignore errors
  hosts: big
  #ignore_errors: yes
  force_handlers: yes
  tasks:
   - name: task1
     copy: src=tmp/myapp1.conf dest=/tmp/
     notify:
      - myhandler1
   - name: task2
     copy: src=tmp/myapp2.conf dest=/tmp/
     notify:
      - myhandler2
   - name: task3
     command: uptime
  handlers:
   - name: myhandler1
     debug: msg="I HAVE EXECUTED TASK1"
   - name: myhandler2
     debug: msg="I HAVE EXECUTED TASK2"
...
