---
- hosts: servera
  tasks:
     - yum: name=httpd state=present
     - service: name=httpd state=started enabled=yes
     - copy: content=Helloworld dest=/var/www/html/index.html
     - firewalld: service=http immediate=yes state=enabled permanent=yes

...
