---
- hosts: servera
  tasks:
  - name: Copy the config file1
    copy:
      src: myapp1.conf
      dest: /etc/myapp1.conf
    notify:
      - restart_myapp1
  - name: Copy the config file2
    copy:
      src: myapp2.conf
      dest: /etc/myapp2.conf
    notify:
      - restart_myapp1
  
  handlers:
    - name: restart_myapp2
      debug:
        msg: "restart myapp"
    - name: restart_myapp1
      debug:
        msg: "restart myapp"
