---
- hosts: servera
  handlers:
    - name: restart_myapp
      debug:
        msg: "restart myapp"
  tasks:
  - name: Copy the config file
    ansible.builtin.copy:
      src: myapp.conf
      dest: /tmp/myapp.conf
    notify:
      - restart_myapp
