---
- name: DEmo of webserver configuration
  hosts: serverd
  tasks:
      - name: OPen firewall port   
        ansible.posix.firewalld:
         service: http
         immediate: yes
         permanent: yes
         state: enabled
