---
- name: Demo
  hosts: servera
  vars:
   myvars:
    - id
    - uname -r
    - uptime
  tasks:
   - name: task1
     ansible.builtin.command:
      "{{item}}"
     loop: "{{myvars}}"
     register: apple
   - name: task2
     ansible.builtin.debug:
      var: apple
...
