---
- name: demo
  hosts: servera
  tasks:
   - name: Grouped set of tasks
     block:
      - name: task1
        ansible.builtin.command: id
      - name: task2
        ansible.builtin.command: notacommand
        #ignore_errors: yes
      - name: task3
        ansible.builtin.command: uptime
     when: ansible_distribution == "RedHat"
     
     rescue:
      - name: Rescue task-restore
        ansible.builtin.command: uname -r
     always:
      - name: cleanup tasks
        ansible.builtin.command: rm -rvf  /tmp/*
        

...
