---
- name: demo
  hosts: all
  #ignore_errors: yes
  tasks:
   - name: task1
     ansible.builtin.command: id
   - name: task2
     ansible.builtin.command: notacommand-no-depended
     ignore_errors: yes
   - name: task3
     ansible.builtin.command: uptime
   - name: task4
     ansible.builtin.command: without-this-the-task5-will-not-work
   - name: task5
     ansible.builtin.command: uname -r

...
