---
  - name: use vhost role playbook
    hosts: webservers

    pre_tasks:
      - debug: msg='Begning web server configuration.'
    tasks:
     - name: role1
       ansible.builtin.import_role: 
        name: myvhost
    
    post_tasks:
      - debug: msg='Web server has been configured.'
        
        
